name: Flutter Workflow
on: 
  release:
    types: [published]
  push:
    branches:
      - "master"
      - "testing-workflows"
jobs:
  build_and_deploy_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter build apk
      - run: flutter build linux
      - name: Compress linux release
        uses: vimtor/action-zip@v1
        with:
          files: build/linux/release/bundle/
          dest: linux-release.zip

      - name: Upload APK to releases
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            build/app/outputs/apk/release/app-release.apk
            build/linux/release/bundle/linux-release.zip
