name: Run Tests
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run_tests:
    name: Run ${{ matrix.target }} Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target: [macOS, Windows, Linux, Android, Web]
        include:
          - os: macos-latest
            target: macOS
            build_target: macos
            build_path: build/macos/Build/Products/Release
            asset_extension: .zip
            asset_content_type: application/zip
          - os: windows-latest
            target: Windows
            build_target: windows
            build_path: build\windows\runner\Release
            asset_extension: .zip
            asset_content_type: application/zip
          - os: ubuntu-latest
            target: Linux
            build_target: linux
            build_path: build/linux/x64/release/bundle
            asset_extension: .tar.gz
            asset_content_type: application/gzip
          - os: ubuntu-latest
            target: Android
            build_target: apk
            build_path: build/app/outputs/flutter-apk
            asset_extension: .apk
            asset_content_type: application/vnd.android.package-archive
          - os: ubuntu-latest
            target: Web
            build_target: web
            build_path: build/web
            asset_extension: .tar.gz
            asset_content_type: application/gzip
      # Disable fail-fast as we want results from all even if one fails.
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
            channel: 'stable'
      - run: flutter pub get
      - run: flutter test
  
